forge 'https://forge.puppet.com'

mod 'puppetlabs-apache', '5.4.0'
mod 'puppetlabs-apt', '7.4.1'
mod 'puppetlabs-amazon_aws', '0.3.0'
mod 'puppetlabs-docker', '3.10.0'
mod 'puppetlabs-inifile', '4.2.0'
mod 'puppetlabs-ntp', '8.3.0'
mod 'puppetlabs-powershell', '3.1.0'
mod 'puppetlabs-puppet_agent', '3.2.0'
mod 'puppetlabs-reboot', '3.0.0'
mod 'puppetlabs-sshkeys_core', '2.0.0'
mod 'puppetlabs-stdlib', '6.3.0'
mod 'puppetlabs-translate', '2.2.0'
