forge 'https://forge.puppet.com'

mod 'puppetlabs-apache', '5.1.0'
mod 'puppetlabs-apt', '7.1.0'
mod 'puppetlabs-amazon_aws', '0.3.0'
mod 'puppetlabs-docker', '3.7.0'
mod 'puppetlabs-inifile', '3.1.0'
mod 'puppetlabs-ntp', '8.1.0'
mod 'puppetlabs-powershell', '2.3.0'
mod 'puppetlabs-puppet_agent', '2.2.0'
mod 'puppetlabs-reboot', '2.2.0'
mod 'puppetlabs-sshkeys_core', '1.0.2'
mod 'puppetlabs-stdlib', '6.1.0'
mod 'puppetlabs-translate', '2.0.0'
